project:
  type: website

website:
  title: "Analysis of Tornado Destruction"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/joanna1016ma
format:
  html:
    theme: cosmo
    css: styles.css
    backgroundcolor: grey
    fontcolor: white



